dist: xenial
language: python

python:
    - 3.7
    - 2.7
    - pypy

matrix:
  fast_finish: true

env:
    - PYTHONHASHSEED=random

install:
    - pip install twisted six
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install --no-binary lxml html5-parser; fi

script: ./setup.py test
